image_width: 1920
image_height: 1080
camera_name: "gopro"
camera_matrix:
  rows: 3
  cols: 3
  data: [900.0, 0.0, 959.5, 0.0, 0.0, 900.0, 539.5, 0.0, 0.0, 0.0, 1.0, 0.0]
distortion_model: none
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.0, 0.0, 0.0, 0.0, 0.0]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]
projection_matrix:
  rows: 3
  cols: 4
  data: [900, 0.0, 959.5, 0.0, 0.0, 900.0, 539.5, 0.0, 0.0, 0.0, 1.0, 0.0]
